stages:
  download:
    cmd: python scripts/download.py --src cmems_obs-sl_eur_phy-ssh_nrt_allsat-l4-duacs-0.125deg_P1D --dst data/raw
    deps:
      - scripts/download.py
    outs:
      - data/raw/SEALEVEL_EUR_PHY_L4_NRT_008_060
  aggregate:
    cmd: python scripts/aggregate.py --src data/raw/SEALEVEL_EUR_PHY_L4_NRT_008_060 --dst data/processed/cmems_obs-sl_eur_phy-ssh_nrt_allsat-l4-duacs-0.125deg_P1D.nc
    deps:
      - scripts/aggregate.py
      - data/raw/SEALEVEL_EUR_PHY_L4_NRT_008_060
    outs:
      - data/processed/cmems_obs-sl_eur_phy-ssh_nrt_allsat-l4-duacs-0.125deg_P1D.nc
