stages:
  download:
    cmd: python scripts/download.py --src cmems_obs-sl_eur_phy-ssh_nrt_allsat-l4-duacs-0.125deg_P1D --dst data/raw
    deps:
      - scripts/download.py
    outs:
      - data/raw/SEALEVEL_EUR_PHY_L4_NRT_008_060
  aggregate:
    cmd: python scripts/aggregate.py --src data/raw/SEALEVEL_EUR_PHY_L4_NRT_008_060 --dst data/processed/cmems_obs-sl_eur_phy-ssh_nrt_allsat-l4-duacs-0.125deg_P1D.nc
    deps:
      - scripts/aggregate.py
      - data/raw/SEALEVEL_EUR_PHY_L4_NRT_008_060
    outs:
      - data/processed/cmems_obs-sl_eur_phy-ssh_nrt_allsat-l4-duacs-0.125deg_P1D.nc
  plot_video:
    cmd: python scripts/plot_video.py --src data/processed/cmems_obs-sl_eur_phy-ssh_nrt_allsat-l4-duacs-0.125deg_P1D.nc --dst reports/cmems_obs-sl_eur_phy-ssh_nrt_allsat-l4-duacs-0.125deg_P1D.mp4
    deps:
      - scripts/plot_video.py
      - data/processed/cmems_obs-sl_eur_phy-ssh_nrt_allsat-l4-duacs-0.125deg_P1D.nc
    outs:
      - reports/cmems_obs-sl_eur_phy-ssh_nrt_allsat-l4-duacs-0.125deg_P1D.mp4
  split:
    cmd: python scripts/split.py --src data/processed/cmems_obs-sl_eur_phy-ssh_nrt_allsat-l4-duacs-0.125deg_P1D.nc --train_dst data/processed/train.nc --test_dst  data/processed/test.nc --test_size 0.2
    deps:
      - scripts/split.py
      - data/processed/cmems_obs-sl_eur_phy-ssh_nrt_allsat-l4-duacs-0.125deg_P1D.nc
    outs:
      - data/processed/train.nc
      - data/processed/test.nc