# Data configuration
dataset: "data/raw/cmems_obs-sl_eur_phy-ssh_my_allsat-l4-duacs-0.0625deg_P1D-224x224.nc"
train: [0, 9188]
valid: [9188, 11487]

variables: ["sla"]
normalize: true
stats_path: "data/interim/stats.json"

# Training defaults
criterion: "mse"
lr: 0.0003
weight_decay: 0.00001
epochs: 100
grad_acc: 1

# System configuration
workers: 8
device: "cpu"
seed: 1337
deterministic: false
save_dir: "runs/"

monitor: 'valid/loss'
mode: 'min'
save_period: -1
patience: 20

tracker:
project: 'ocean surface level'

# Plot video
start_date: '2022-01-01'
end_date: '2022-01-31'
